name: Build and Test .NET 9 Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  SHOULD_PUBLISH: true

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
          cache: true
          cache-dependency-path: "**/packages.lock.json"

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the project
        run: dotnet build --configuration Release --no-restore
        
      - name: Publish the project
        if: ${{ env.SHOULD_PUBLISH }}
        run: dotnet publish --configuration Release --no-build --output ./publish
        
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: published-artifacts-${{ github.run_number }}
          path: ./publish/
          retention-days: 30

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Run tests
        run: dotnet test

  deploy:
    runs-on: ubuntu-latest
    needs: [build, test]
    if: |
      !cancelled() && 
      needs.test.result == 'success' && 
      (needs.build.result == 'success' || needs.build.result == 'skipped')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy application
        run: |
          echo "Deploying application..."

  deploy-reusable:
    name: Deploy Reusable Workflow
    needs: [build, test]
    uses: ./.github/workflows/deploy-app.yml
    with:
      message: "Deployment triggered by workflow run"
    secrets: inherit