name: Deployment to Web Application

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag for the deployment'
        required: true
        type: string
  workflow_call:
    inputs:
      message:
        description: 'Message for the deployment'
        required: true
        type: string

jobs:
  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy to Server
        run: echo "Deploying to server..."

      - name: Post Deployment Message
        run: echo "${{ inputs.message }}"